language: php

services:
  - mysql

php:
    - 7.2

install:
    - composer install
    - php bin/console doctrine:database:create
    - php bin/console doctrine:migrations:diff
    - php bin/console doctrine:migrations:migrate

script:
    - ./bin/phpunit
