language: php

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client

services:
    - mysql

env:
    global:
        - DATABASE_URL=mysql://root:@127.0.0.1:3306/test
        - APP_ENV=dev

php:
    - 7.2

before_install:
    - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
    - sudo mysql_upgrade
    - sudo service mysql restart

install:
    - composer install
    - php bin/console doctrine:database:create
    - php bin/console doctrine:migrations:diff
    - php bin/console doctrine:migrations:migrate -n

script:
    - ./bin/phpunit
